ARG RUNTIME_BASE_IMAGE=enflame:ubuntu_qwen3_0522
FROM ${RUNTIME_BASE_IMAGE} AS build

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && sed -i 's@http://archive.ubuntu.com/@https://mirrors.tuna.tsinghua.edu.cn/@g' /etc/apt/sources.list

ENV DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai

RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3 \
    python3-pip \
    wget \
    tzdata \
    iproute2 \
    tini \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip cache purge && \
    pip install poetry==1.8.3

COPY . /workspace/gpustack
RUN cd /workspace/gpustack && make build

FROM ${RUNTIME_BASE_IMAGE} AS runtime

COPY --from=build /workspace/gpustack/dist/*.whl /dist/
RUN pip install /dist/*.whl && \
    pip cache purge && \
    rm -rf /dist

RUN gpustack download-tools

ENTRYPOINT [ "tini", "--", "gpustack", "start" ]