{
 "title": "Seabed LLM Serving Runtime",
 "description": "Monitoring Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(seabed:cluster_info,cluster_name)"
    }
   },
   {
    "name": "model_name",
    "label": "Model",
    "query": {
     "query": "label_values(seabed:model_info{cluster_name=\"$cluster_name\"},model_name)"
    }
   },
   {
    "name": "model_instance_name",
    "label": "Model Instance",
    "query": {
     "query": "label_values(seabed:generation_tokens_total{model_name=\"$model_name\", cluster_name=\"$cluster_name\"},model_instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Desired Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seabed:model_desired_instances{cluster_name=\"$cluster_name\", model_name=\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seabed:model_running_instances{cluster_name=\"$cluster_name\",model_name=\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seabed:model_desired_instances{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}) - sum(seabed:model_running_instances{cluster_name=\"$cluster_name\",model_name=\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seabed:num_requests_running{cluster_name=\"$cluster_name\",model_name=\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(seabed:num_requests_waiting{cluster_name=\"$cluster_name\",model_name=\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seabed:model_info{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seabed:model_info{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Source Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seabed:model_info{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Source",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seabed:model_info{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Requests per Minute",
   "type": "timeseries",
   "description": "Total request per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "increase(seabed:e2e_request_latency_seconds_count{cluster_name=\"$cluster_name\",model_name=~\"$model_name\", model_instance_name=~\"$model_instance_name\"}[1m])",
     "legendFormat": "Requests/min({{model_instance_name}})"
    }
   ]
  },
  {
   "title": "Model Token Generation Throughput",
   "type": "timeseries",
   "description": "Number of tokens generation per second for current model",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(seabed:generation_tokens_total{cluster_name=\"$cluster_name\",model_name=\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec (Total) "
    }
   ]
  },
  {
   "title": "End-to-End Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_instance_name) (rate(seabed:e2e_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P99({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_instance_name) (rate(seabed:e2e_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P95({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_instance_name) (rate(seabed:e2e_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P90({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_instance_name) (rate(seabed:e2e_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P50({{model_instance_name}})"
    },
    {
     "expr": "rate(seabed:e2e_request_latency_seconds_sum{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])\n/\nrate(seabed:e2e_request_latency_seconds_count{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Average({{model_instance_name}})"
    }
   ]
  },
  {
   "title": "End-to-End Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(seabed:e2e_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=~\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Runtime Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Runtime Status",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "seabed:num_requests_running{cluster_name=\"$cluster_name\",model_instance_name=~\"$model_instance_name\", model_name=\"$model_name\"}",
     "legendFormat": "Num Running({{model_instance_name}})"
    },
    {
     "expr": "seabed:num_requests_swapped{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}",
     "legendFormat": "Num Swapped({{model_instance_name}})"
    },
    {
     "expr": "seabed:num_requests_waiting{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}",
     "legendFormat": "Num Waiting({{model_instance_name}})"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(seabed:prompt_tokens_total{cluster_name=\"$cluster_name\", model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec {{model_instance_name}}"
    },
    {
     "expr": "rate(seabed:generation_tokens_total{cluster_name=\"$cluster_name\", model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec {{model_instance_name}}"
    },
    {
     "expr": "sum(rate(seabed:prompt_tokens_total{cluster_name=\"$cluster_name\", model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval]))",
     "legendFormat": "Prompt Tokens/Sec (Total)"
    },
    {
     "expr": "sum(rate(seabed:generation_tokens_total{cluster_name=\"$cluster_name\", model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec (Total)"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_instance_name) (rate(seabed:time_to_first_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P99({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_instance_name) (rate(seabed:time_to_first_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P95({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_instance_name) (rate(seabed:time_to_first_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P90({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_instance_name) (rate(seabed:time_to_first_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P50({{model_instance_name}})"
    },
    {
     "expr": "rate(seabed:time_to_first_token_seconds_sum{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])\n/\nrate(seabed:time_to_first_token_seconds_count{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Average({{model_instance_name}})"
    }
   ]
  },
  {
   "title": " Inter Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_instance_name) (rate(seabed:inter_token_latency_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P99({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P95({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P90({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P50({{model_instance_name}})"
    },
    {
     "expr": "rate(seabed:time_per_output_token_seconds_sum{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])\n/\nrate(seabed:time_per_output_token_seconds_count{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Mean({{model_instance_name}})"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by LLM Serving Runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "seabed:kv_cache_usage_ratio{cluster_name=\"$cluster_name\",model_name=~\"$model_name\",model_instance_name=~\"$model_instance_name\"}",
     "legendFormat": "{{model_instance_name}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "seabed:prefix_cache_hit_rate{model_name=~\"$model_name\",model_instance_name=~\"$model_instance_name\"}",
     "legendFormat": "{{model_instance_name}}"
    },
    {
     "expr": "rate(seabed:prefix_cache_hits_total{cluster_name=\"$cluster_name\",model_name=~\"$model_name\",model_instance_name=~\"$model_instance_name\"}[1m]) / rate(seabed:prefix_cache_queries_total{cluster_name=\"$cluster_name\",model_name=~\"$model_name\",model_instance_name=~\"$model_instance_name\"}[1m])",
     "legendFormat": "{{model_instance_name}}"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by(le) (increase(seabed:request_prompt_tokens_bucket{model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\", cluster_name=\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by(le) (increase(seabed:request_generation_tokens_bucket{model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\", cluster_name=\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Per output token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\", cluster_name=\"$cluster_name\"}[$__rate_interval])))",
     "legendFormat": "P99({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P95({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P90({{model_instance_name}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_instance_name) (rate(seabed:time_per_output_token_seconds_bucket{cluster_name=\"$cluster_name\",model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\"}[$__rate_interval])))",
     "legendFormat": "P50({{model_instance_name}})"
    },
    {
     "expr": "rate(seabed:time_per_output_token_seconds_sum{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])\n/\nrate(seabed:time_per_output_token_seconds_count{cluster_name=\"$cluster_name\",model_name=\"$model_name\",model_instance_name=~\"$model_instance_name\"}[$__rate_interval])",
     "legendFormat": "Mean({{model_instance_name}})"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(finished_reason, model_instance_name) (increase(seabed:request_success_total{model_name=\"$model_name\", model_instance_name=~\"$model_instance_name\", cluster_name=\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{finished_reason}}({{model_instance_name}})"
    }
   ]
  }
 ]
}